### ISSUE TITLE
sha1 not supported error

### ISSUE THREAD

**Issue by equinusocio** [iamcco/gh-pages-webpack-plugin#1]
I get this error when i require the lib
```
Module build failed: Error: Algorithm "sha1"  not supported. supported values: passthrough
    at applyDefaults (/Users/equinusocio/Repositories/Private/material-theme/node_modules/object-hash/index.js:89:11)

    at objectHash (/Users/equinusocio/Repositories/Private/material-theme/node_modules/object-hash/index.js:31:13)
    at Object.module.exports (/Users/equinusocio/Repositories/Private/material-theme/node_modules/eslint-loader/index.js:155:20)
```

**Comment by iamcco** [comment]
It seems that isn't the plugin's issues.

**Comment by qgustavor** [comment]
Can you just update the gh-pages dependency so [this bug](https://github.com/tschaub/gh-pages/issues/42) gets fixed?

**Comment by iamcco** [comment]
@qgustavor done
